# Lectura de los datos

In [5]:
import pandas as pd

df = pd.read_excel('archivo_sin_duplicados.xlsx')

columnas = df.columns

df.head()

,Marca temporal,Fecha de Ingreso,Primer Nombre,Segundo Nombre,Primer Apellido,Segundo Apellido,Número de identidad del huésped (Separado por guiones),Lugar de procedencia,"Aldea, barrio o colonia",Teléfono celular (Separado con guión en medio),...,Condición,Número de identidad del afiliado (Separado con guiones),Teléfono celular del afiliado (Separado con guión en medio),Patrono,Nombre del paciente,Parentesco con el huésped,Teléfono celular del paciente (Separado con guión en medio),Causa de visita al IHSS,Observaciones,Unnamed: 26
0,2017-07-03 15:31:14.890,2017-07-03 00:00:00,AXEL,FRANCISCO,ORELLANA,FERNANDEZ,0501-1998-09900,VILLANUEVA,PUEBLO NUEVO,9676-8474,...,Afiliado,1620-1994-00463,98573268,DELTA CORTES,HIJO DE YENY YAMILETH PEREZ,MADRE,MILSMO AFILIADO,Consulta médica,NaN,NaN
1,2017-07-03 15:33:33.219,2017-07-03 00:00:00,YENI,YAMILETH,PEREZ,FERNANDEZ,1620-1994-00463,VILLANUEVA,PUEBLO NUEVO,9857-3268,...,Afiliado,MISMA HUESPED,MISMA HUESPED,DELTA CORTES,HIJO DE HUESPED,HIJO,MISMO HUESPED,Consulta médica,NaN,NaN
2,2017-07-03 17:42:09.427,2017-07-03 00:00:00,JOSE,ANGEL,SANTOS,ZUNIGA,0103-1987-00280,TOCOA,ALDEA LERIDA,9996-8137,...,Afiliado,0209-1989-01037,9886-3116,COAPALMA-TOCOA,MISMO AFILIADO,PADRE,MISMO AFILIADO,Quimioterapia o radioterapia,NaN,NaN
3,2017-07-03 17:49:08.166,2017-07-03 00:00:00,LUIS,ALONSO,MATUTE,NaN,0209-1989-01037,TOCOA,ALDEA LERIDA,9886-3116,...,Afiliado,MISMO HUESPED,MISMO HUESPED,COAPALMA-TOCOA,MISMO HUESPED,MISMO HUESPED,MISMO HUESPED,Quimioterapia o radioterapia,NaN,NaN
4,2017-07-07 10:10:51.756,2017-07-07 00:00:00,LETICIA,YOSELIN,LOPEZ,FUENTES,0209-1997-02856,COLON,QUEBRADA DE ARENA,3316-9450,...,Afiliado,0209-2017-00828,3316-9450,EXPORTADOR DEL ATLANTICO,MARIO ALBERTO MOLINA LOPEZ,HIJO,MISMO HUESPED,Ingresado por enfermedad,NaN,NaN

In [6]:
df.tail()

,Marca temporal,Fecha de Ingreso,Primer Nombre,Segundo Nombre,Primer Apellido,Segundo Apellido,Número de identidad del huésped (Separado por guiones),Lugar de procedencia,"Aldea, barrio o colonia",Teléfono celular (Separado con guión en medio),...,Condición,Número de identidad del afiliado (Separado con guiones),Teléfono celular del afiliado (Separado con guión en medio),Patrono,Nombre del paciente,Parentesco con el huésped,Teléfono celular del paciente (Separado con guión en medio),Causa de visita al IHSS,Observaciones,Unnamed: 26
6758,2024-04-16 16:31:26,2024-04-16 00:00:00,MIRNA,LETICIA,NAVARRO,RODRIGUEZ,1303-1998-00139,CANDELARIA LEMPIRA,CASTAÑO,9764-2978,...,NaN,NaN,NaN,NaN,BLANCA RODRIGUEZ,HERMANA,NaN,RECIENDO NACIDO,Remitida HNMCR,NaN
6759,2024-04-16 17:15:33,2024-04-16 00:00:00,DEYSI,NaN,FUENTES,NaN,0414-1968-00031,SANTA ROSA DE COPAN,LOS CEDROS,9556-5987,...,NaN,NaN,NaN,NaN,FLOR FUENTES,MADRE,NaN,"Dado de alta, en recuperación",NaN,NaN
6760,2024-04-16 17:20:33,2024-04-16 00:00:00,FLOR,DE MARIA,FUENTES,NaN,0318-2003-01013,SANTA ROSA DE COPAN,LOS CEDROS,9556-5987,...,NaN,NaN,NaN,NaN,FLOR FUENTES,ELLA MISMA,NaN,"Dado de alta, en recuperación",NaN,NaN
6761,2024-04-17 16:35:23,2024-04-17 00:00:00,SARA,YAQUELINE,PONCE,MARTINEZ,1627-1994-00423,SANTA BARBARA LAS VEGAS,EL PLANON,8924-5207,...,NaN,NaN,NaN,NaN,GENESIS STEVEN ERAZO PONCE,HIJO,NaN,Consulta Medica,NaN,NaN
6762,2024-04-18 17:19:43,2024-04-18 00:00:00,GILMA,ARACELI,SOLIZ,NaN,1507-1964-00015,ESQUIPULAS DEL NORTE / OLANCHO,BARRIO ABAJO,3772-0348,...,NaN,NaN,NaN,NaN,ELLA MISMA,ELLA MISMA,NaN,Consulta médica,CITA EN UROLOGIA,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6763 entries, 0 to 6762
Data columns (total 27 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   Marca temporal                                               6752 non-null   datetime64[ns]
 1   Fecha de Ingreso                                             6763 non-null   object
 2   Primer Nombre                                                6763 non-null   object
 3   Segundo Nombre                                               5542 non-null   object
 4   Primer Apellido                                              6762 non-null   object
 5   Segundo Apellido                                             5599 non-null   object
 6   Número de identidad del huésped (Separado por guiones)       6749 non-null   object
 7   Lugar de procedencia                                         6750 non-null   object
 8   Aldea, barrio o colonia                                      6686 non-null   object
 9   Teléfono celular (Separado con guión en medio)               6543 non-null   object
 10  Sexo                                                         6763 non-null   object
 11  Edad                                                         6763 non-null   int64
 12  Profesión u oficio                                           6613 non-null   object
 13  Es primera vez                                               6763 non-null   object
 14  Cama                                                         6760 non-null   object
 15  Iglesia                                                      6726 non-null   object
 16  Nombre completo del afiliado                                 3308 non-null   object
 17  Condición                                                    3244 non-null   object
 18  Número de identidad del afiliado (Separado con guiones)      639 non-null    object
 19  Teléfono celular del afiliado (Separado con guión en medio)  561 non-null    object
 20  Patrono                                                      3348 non-null   object
 21  Nombre del paciente                                          6761 non-null   object
 22  Parentesco con el huésped                                    6739 non-null   object
 23  Teléfono celular del paciente (Separado con guión en medio)  205 non-null    object
 24  Causa de visita al IHSS                                      6757 non-null   object
 25  Observaciones                                                4519 non-null   object
 26  Unnamed: 26                                                  1 non-null      object
dtypes: datetime64[ns](1), int64(1), object(25)
memory usage: 1.4+ MB

In [8]:
df.describe()

                      Marca temporal         Edad
count                           6752  6763.000000
mean   2021-01-29 18:24:48.349937920    38.108088
min       2017-07-03 15:31:14.890000     1.000000
25%    2019-01-22 12:41:07.363000064    26.000000
50%    2021-08-17 14:04:38.487500032    36.000000
75%    2022-12-28 15:44:48.021000192    48.000000
max              2025-02-25 17:44:02    92.000000
std                              NaN    14.605550

# Limpieza de datos

## Limpiando datos del afiliado (Identidad)

In [11]:
#Vamos a crear un diccionario para incluir todas las variaciones de "mismo huesped" 

mismos = ["M. H.", "M.H.", "MH.", "MISMA HUESPED", "MISMO HUESPED"]

In [28]:


def actualizar_identidad(row):
    if row['Número de identidad del afiliado (Separado con guiones)'] in mismos:
        return row['Número de identidad del huésped (Separado por guiones)']
    else:
        return row['Número de identidad del afiliado (Separado con guiones)']


df['Número de identidad del afiliado (Separado con guiones)'] = df.apply(actualizar_identidad, axis=1)

df.to_excel('CORREGIDO_modificado.xlsx', index=False)